### ISSUE TITLE
Parsing by parts sometimes returns not whole strings

### ISSUE THREAD

**Issue by allmycode** [anatolygudkov/green-jelly#1]
to fix this 
`stringBuilder.append(data, startStringPos, pos - startStringPos);`
need to be added after line `JsonParser:439` to save state.
Please take a look.

**Comment by allmycode** [comment]
and after `JsonParser:561` too `stringBuilder.append(data, startStringPos, pos - startStringPos);`

**Comment by allmycode** [comment]
pr attached 
https://github.com/anatolygudkov/green-jelly/pull/2

**Comment by anatolygudkov** [comment]
Thank you very much for your report. The issue with partially processed strings seems to be fixed on our side by now. We really needed JsonParser:561 too stringBuilder.append(data, startStringPos, pos - startStringPos); as you commented on Aug 7. And we also have a change which equals to your JsonParser:439 but in another place. We have updated tests and now they are OK. So, I'm closing the issue as fixed.
